export enum RESULT_CODE {
	SUCCESS = 200,

	INVALID_PAYLOAD = -1,
	
	NOT_YET_IMPLEMENTED = -60,

	EMAIL_ALREADY_REGISTERED = -100,
	USERNAME_ALREADY_REGISTERED = -101,
	EMAIL_DOES_NOT_EXIST = -102,
	INVALID_PASSWORD = -103,

	INVALID_FIELD_AMMOUNT = -104,	//When fetching information, not enough selection fields provided

	INVALID_TOKEN = -115,

	INSUFFICIENT_FUNDS = -300,

	OPEN_ORDER_NOT_FOUND = -400,
	USER_NOT_FOUND = -401,
	BITCOIN_PRICE_NOT_FOUND = -402,
	OPEN_POSITION_NOT_FOUND = -403,
	UNKNOWN_ROUTE = -420,

	INTERNAL_ERROR = -500,
	ERROR_CANCELING_ORDER = -501,
	OPEN_POSITION_NOT_CREATED = -502,
	ERROR_CLOSING_AMP = -503,
	OPEN_ORDER_NOT_CREATED = -504,
	ERROR_MAKING_DEPOSIT = -505,
}

export enum UI_RESULT_CODE {
	SUCCESS = 200,
	INVALID_DATA = -1,
	ERROR_INSERTING_DATA = -20,
	INVALID_TABLE_NAME = -21,
	AUTH_INVALID = -22,
	PROFILE_IMAGE_TOO_BIG = -23
}

export enum AUTH_STATE_CHANGE {
	LOGGED_IN = 25,
	LOGGED_OUT = 26,
	CHANGED = 27	//Loaded state, unspecified (i.e., when the app first starts)
}

export enum SUCCESS_UI {
	CREATED_ACCOUNT = 24,
	LOGGED_IN = 25,
	LOGGED_OUT = 26,
	CHANGED_PASSWORD = 27,
	ADDED_OPEN_ORDER = 28,
	ADDED_OPEN_POSITION = 29,
	CANCELLED_OPEN_ODER = 30,
	CLOSED_OO_AMP = 31,	//Closed Open Order At Market Price
	DEPOSIT_MADE = 32,
}

export enum ORDERBOOK_CODE { 
	UPDATED = "1"
}

export enum RECENT_TRADES_CODE {
	UPDATED = "1"
}

export const UID_REPLACEMENT = "_UID_";